### ISSUE TITLE
运行一段时间后报错

### ISSUE THREAD

**Issue by polinload** [boy-hack/w8fuckcdn#2]
你好，我用了下你的fuckcdn，是先get_ips找二级域名的IP，再执行fuckcdn.py
但是报错，信息如下：

Traceback (most recent call last):
  File "fuckcdn.py", line 181, in <module>
    main()
  File "fuckcdn.py", line 172, in main
    hackhttp = HttpTest(config.host,config.keyword,result.keys(),config.timeout)
  File "fuckcdn.py", line 125, in __init__
    self.outfile = open(self.filename, 'w')
IOError: [Errno 2] No such file or directory: 'E:\\Downloads\\w8fuckcdn-master\\w8fuckcdn-master\\result\\www.bitmain.com.log'

win和Linux上面我都试了，不知道是我操作失误，还是因为什么，麻烦作者看下，非常感谢作者的开源精神

**Comment by boy-hack** [comment]
在根目录下要新建一个result目录存放结果，怪我没有完全提交 -
